version: '2.1'

volumes:
  jwtproject:

services:
  mysql:
    image: mysql:8
    container_name: MYSQL
    environment:
      - MYSQL_DATABASE=JwtProject
      - MYSQL_ROOT_PASSWORD=0606
    ports:
      - 3306:3306
    volumes:
      - jwtproject:/var/lib/mysql